create table Teacher(
                        id int generated by default as identity primary key ,
                        name varchar (100) not null,
                        surname varchar (100) not null
);

create table Student(
                        id int generated by default as identity primary key ,
                        name varchar (100) not null,
                        surname varchar (100) not null,
                        name_of_group varchar (100) not null

);